version: "2.0"
nlu:
- intent: start
  examples: |
    - start
- intent: TanyaDosen
  examples: |
    - Minta daftar dosen yang berjurusan [teknik informatika](jurusan)
    - Berapa NIP dosen dengan nama [abdiansyah](nama_dosen) ?
    - Siapa dosen PA mahasiswa yang memiliki [NIM 0902118182XXXX](nim) ?
    - Siapa saja dosen dari jurusan [teknik informatika](jurusan) yang berjenis kelamin [laki-laki](gender) ?
    - Berapa nip dosen yang memiliki nama [naufal](nama_dosen) ?
    - Berikan data dosen pembimbing dari mahasiswa yang bernama [Febyk](nama_mahasiswa)
    - sebutkan nomor induk pegawai dari dosen yang memiliki nama mengandung kata [santoso](nama_dosen)
    - Berikan data dosen pembimbing dari mahasiswa yang bernama [Adi](nama_mahasiswa)
    - tampilkan daftar nama dosen
    - Siapa saja dosen [teknik informatika](jurusan) yang berjenis kelamin [perempuan](gender) ?
    - Temukan nama dosen yang memiliki NIP [909231902](nip)
    - Berapa nip dosen yang bernama [qurhanul](nama_dosen) ?
    - Berikan data dosen pembimbing dari mahasiswa yang bernama [Nadia](nama_mahasiswa)
    - Cari nama dosen [laki laki](gender) [teknik informatika](jurusan)
    - Tampilkan profil dosen dengan nama berawalan kata [nabila](nama_dosen)
    - Tampilkan dosen PA dari mahasiswa
- intent: TanyaDenganKondisi
  examples: |
    - Tolong carikan nama mahasiswa yang [angkatan 2018](angkatan) urutkan [berdasarkan NIM](order_by_desc) secara menurun
    - temukan data dosen urutkan [berdasarkan nip](order_by_desc) meningkat [nama](nama_dosen) menurun
    - temukan data dosen [batasi 5](limit) data
    - Tampilkan ipk , dan nama mahasiswa yang [berangkatan 2018](angkatan) urutkan [berdasarkan ipk](order_by_desc) menurun [batasi 10](limit) data
    - tampilkan nama mahasiswa secara unik yang memiliki nim [berawalan 090210](nim) [atau]{"entity": "condition", "value": "or"} nim [berawalan 090211](nim) [dan]{"entity": "condition", "value": "and"} [angkatan 2018](angkatan) [atau]{"entity": "condition", "value": "or"} angkatan [diatas]{"entity": "condition", "value": "more than"} [angkatan 2019](angkatan) dengan jenis kelamin [laki laki](gender) [batasi 5](limit) data urutkan [berdasarkan nim](order_by)
    - Cari data mahasiswa yang memiliki nilai Suliet [lebih dari]{"entity": "condition", "value": "more than"} [enam ratus](nilai_suliet)
    - tampilkan nama matakuliah dengan kode diakhiri [angka 10](kode) [batasi 2](limit) data
    - Berikan data mahasiswa dengan IPK [kurang dari]{"entity": "condition", "value": "less than"} [tiga](ipk)
    - Tampilkan mahasiswa dengan IPK [diatas]{"entity": "condition", "value": "more than"} [tiga](ipk)
    - temukan mahasiswa dengan nama berawalan [kata adi](nama_mahasiswa) [dan]{"entity": "condition", "value": "and"} [angkatan 2018](angkatan) [atau]{"entity": "condition", "value": "or"} [lebih besar dari]{"entity": "condition", "value": "more than"} [angkatan 2018](angkatan)
    - siapa mahasiswa dengan ipk [dibawah]{"entity": "condition", "value": "less than"} [dua](ipk)
    - temukan daftar mahasiswa dengan [angkatan 2018] [dan]{"entity": "condition", "value": "and"} jurusan [teknik informatika](jurusan)
    - tampilkan data mahasiswa dengan nama mengandung [kata awan](nama_mahasiswa) dan tahun [angkatan 2018](angkatan) [atau]{"entity": "condition", "value": "or"} [angkatan 2019](angkatan)
    - sebutkan nama mata kuliah pada [semester 6](semester) urutkan [berdasarkan nama](order_by) dan [batasi 9](limit_unique) data secara unik
    - Tampilkan daftar nama mahasiswa yang memiliki ipk [lebih besar]{"entity": "condition", "value": "more than"} [tiga koma lima](ipk)
    - sebutkan mahasiswa yang [nilai sulietnya 500](nilai_suliet)
    - tampilkan daftar nama mahasiswa dari [jurusan ti]{"entity": "jurusan", "value": "teknik informatika"} yang nilai sulietnya [diatas]{"entity": "condition", "value": "more than"} [lima ratus](nilai_suliet) [dan]{"entity": "condition", "value": "and"} angkatan [diatas]{"entity": "condition", "value": "more than"} [angkatan 2018](angkatan)
    - Berikan data mahasiswa dengan IPK [lebih dari]{"entity": "condition", "value": "more than"} [tiga](ipk)
    - tampilkan nama dosen dengan nama [diawali huruf a](nama_dosen) dan nip [diawali angka 1](nip) urutkan [berdasarkan nip](order_by) [batasi 5](limit_unique) data secara unik
    - Tampilkan nama mahasiswa dengan IPK [lebih besar dari]{"entity": "condition", "value": "more than"} [tiga](ipk) [batasi 5](limit) data
- intent: TanyaMataKuliah
  examples: |
    - semester berapakah mata kuliah dengan nama mengandung kata [kp]{"entity": "mata_kuliah", "value": "kerja praktek"}
    - tampilkan sks dan kode mata kuliah dengan nama [Technopreneurship](mata_kuliah)
    - Apa saja mata kuliah pilihan yang bisa diambil pada [semester 6](semester) ?
    - Tampilkan sks pada mata kuliah dengan nama [kalkulus](mata_kuliah)
    - Berapa jumlah SKS untuk mata kuliah dengan nama [kalkulus](mata_kuliah) ?
    - Apa nama dan sks mata kuliah dengan kode [FIK20022](kode) ?
    - sebutkan mata kuliah pilihan pada [semester 5](semester)
    - Apa nama mata kuliah dengan kode [FIK23222](kode) ?
    - sebutkan daftar nama mata kuliah dengan nama yang mengandung kata [web](mata_kuliah)
    - tampilkan Satuan Kredit Semester mata kuliah dengan nama yang mengandung kata [kripto](mata_kuliah)
    - sebutkan daftar mk yang memiliki [sks 4](sks)
    - carikan data mata kuliah dengan kode [FIK002317](kode)
    - tampilkan data mata kuliah
    - sebutkan daftar nama mata kuliah dengan nama yang mengandung kata [android](mata_kuliah)
    - tolong cari kode dari mata kuliah dengan nama [kalkulus](mata_kuliah)
    - semester berapakah mata kuliah dengan nama mengandung kata [skripsi](mata_kuliah)
    - tampilkan daftar mk pada [semester 7](semester)
    - sebutkan mata kuliah pilihan pada [semester 7](semester)
    - sebutkan daftar nama mata kuliah dengan nama yang mengandung kata [game](mata_kuliah)
    - sebutkan daftar mk yang memiliki [sks 2](sks)
    - Temukan kode mata kuliah dengan nama [Probabilitas dan Statistika](mata_kuliah)
    - Tolong temukan daftar mata kuliah
    - Temukan nama matakuliah yang memiliki Kode [FIK001XXX](kode)
    - tampilkan data daftar mk
    - Temukan kode mata kuliah dengan nama [kalkulus](mata_kuliah)
- intent: TanyaMahasiswa
  examples: |
    - tampilkan nim mahasiswa yang namanya [jamal](nama_mahasiswa)
    - Temukan data mahasiswa dengan nama [adi](nama_mahasiswa)
    - tampilkan nama mahasiswa yang jenis kelaminnya [perempuan](gender)
    - tampilkan mahasiswa dengan [program studi Bilingual](prodi) [angkatan 2018](angkatan) ?
    - sebutkan nomor induk mahasiswa dan nama dari mahasiswa yang [berangkatan dibawah 2019](angkatan)
    - Tampilkan tahun angkatan dari mahasiswa
    - Tampilkan daftar nama mahasiswa yang berjenis kelamin [perempuan](gender) pada [jurusan TI]{"entity": "jurusan", "value": "teknik informatika"} [angkatan 2018](angkatan)
    - tampilkan data mahasiswa dengan nomor induk mahasiswa yaitu [09021181823168](nim)
    - Tampilkan daftar nama mahasiswa dengan jurusan berakhiran kata [Informatika](jurusan) dan [program studi Reguler](prodi) dan tahun [angkatan 2015](angkatan)
    - berikan data mahasiswa dengan [ipk 4](ipk)
    - Tolong berikan daftar nama mahasiswa yang berjenis kelamin [wanita](gender)
    - berapa nilai suliet mahasiswa dengan [nim 09021181823003](nim)
    - Siapa nama mahasiswa yang memiliki [NIM 09021281823039](nim) ?
    - tampilkan mahasiswa dengan dosen pembimbing [abdiansyah](nama_dosen)
    - berikan data nim, dan nama seluruh mahasiswa
    - Siapa nama mahasiswa yang memiliki [nim 09021281823057](nim)
    - tampilkan nama mahasiswa
    - temukan mahasiswa yang berjenis kelamin [wanita](gender)
    - siapa nama mahasiswa dan tahun angkatan dengan [nim 09021281823057](nim)
    - Tampilkan mahasiswa teknik informatika [angkatan 2017](angkatan)
    - tampilkan nama dan nilai suliet dari mahasiswa urutkan berdasarkan nilai suliet meningkat
    - Siapakah mahasiswa dengan [NIM 09021281823172](nim) ?
    - tampilkan mahasiswa
    - Berapa IPK mahasiswa dengan [NIM 0902181823003](nim) ?
    - Tampilkan daftar jurusan dari mahasiswa secara unik
    - Tampilkan daftar nama mahasiswa yang berjenis kelamin [perempuan](gender) pada jurusan [Informatika](jurusan) [angkatan 2018](angkatan)
    - Tampilkan data NIM seluruh mahasiswa dengan [angkatan 2018](angkatan)
    - Temukan nama mahasiswa yang memiliki [NIM 09021181823168](nim)
    - Tampilkan NIM mahasiswa
    - Tolong cari daftar nama mahasiswa
    - Tampilkan data mahasiswa yang bernama [Dahlia](nama_mahasiswa)
    - Tampilkan data NIM seluruh mahasiswa yang [angkatan 2018](angkatan)
    - temukan angkatan mahasiswa secara unik
    - Tampilkan daftar nama mahasiswa yang berjenis kelamin [pria](gender)
    - Berapa nim mahasiswa dengan nama mengandung kata [virani](nama_mahasiswa) ?
    - sebutkan Indeks Prestasi Kumulatif mahasiswa dengan [nim 0902xxxxx](nim)
    - Siapa nama mahasiswa yang memiliki [NIM 0902118182XXXX](nim) ?
    - tampilkan data mahasiswa
- synonym: Fakultas Ilmu Komputer
  examples: |
    - FIK
- synonym: kerja praktek
  examples: |
    - kp
- synonym: algoritma dan pemrograman
  examples: |
    - alpro
- synonym: teknik informatika
  examples: |
    - jurusan TI
    - jurusan ti
- synonym: or
  examples: |
    - atau
- synonym: and
  examples: |
    - dan
- synonym: more than
  examples: |
    - diatas
    - lebih besar dari
    - lebih dari
    - lebih besar
- synonym: less than
  examples: |
    - kurang dari
    - dibawah
